services:
  - type: web
    name: telegram-uploader-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: CHAT_ID
        value: your_chat_id_here
